name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

    env:
      Solution_Name: Chirp.sln                         # Replace with your solution name
      Test_Project_Path: test/test.csproj                # Replace with the path to your test project

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core SDK
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.410

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the test project
    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path --configuration ${{ matrix.configuration }}

    # Restore the application
    - name: Restore the application
      run: dotnet restore $env:Solution_Name --configuration ${{ matrix.configuration }}

    # Build the application
    - name: Build the application
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

    # Publish the application
    - name: Publish the application
      run: dotnet publish $env:Solution_Name --configuration ${{ matrix.configuration }} -o ./publish
