name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup8chirprazor

on:
  workflow_run:
    workflows: ['Release Workflow']
    types: [completed]
    branches:
      - End2end
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allow manual dispatch

jobs:
  build-on-azure:
    runs-on: ubuntu-latest
    env:
      authentication_github_clientId: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTID }}
      authentication_github_clientSecret: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTSECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Build & Install
        run: dotnet build
      
      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Install Playwright browsers
        run: playwright install
    
      # Run tests
      - name: Run tests
        env:
          authentication_github_clientId: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTID }}
          authentication_github_clientSecret: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTSECRET }}
        run: dotnet test --configuration Release --verbosity normal

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A2FE0A6C465E42579128A9BE63443BB8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_315C864B1A994BD1B4F26EF33C455303 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_11DCAC46CC9D4313A3FACF3C59F7C168 }}

      - name: Set up environment variables
        run: |
          echo "GITHUBCLIENTID=${{ secrets.GITHUBCLIENTID }}" >> $GITHUB_ENV
          echo "GITHUBCLIENTSECRET=${{ secrets.GITHUBCLIENTSECRET }}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup8chirprazor'
          slot-name: 'Production'
          package: .
