name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build, Test, and Release Chirp Executable

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build Chirp.sln --configuration Release --no-restore

    # Run tests with target framework specified
    - name: Run tests
      run: dotnet test Chirp.sln --framework net7.0 --no-build --verbosity normal

    # Build for Windows (x64) and create single EXE file
    - name: Build and Publish Single EXE for Windows (x64)
      run: dotnet publish src/Chirp.CLI.Client/Chirp.CLI.Client.csproj -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true --output ./publish/win-x64

    # Compress the EXE into a ZIP file
    - name: Compress EXE to ZIP
      run: zip -j ./publish/chirp-win-x64.zip ./publish/win-x64/Chirp.CLI.Client.exe

    # Create GitHub Release and attach only the ZIP file
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./publish/chirp-win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
