name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build, Test, and Release Chirp Executable
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
            archive: tar.gz
          - kind: windows
            os: windows-latest
            target: win-x64
            archive: zip
          - kind: macOS
            os: macos-latest
            target: osx-x64
            archive: tar.gz
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.x

    - name: Restore dependencies
      run: dotnet restore Chirp.sln

    - name: Build the solution
      run: dotnet build Chirp.sln --configuration Release

    - name: Run tests
      run: dotnet test Chirp.sln --configuration Release --verbosity normal

    - name: Publish the application
      run: |
        tag=$(git describe --tags --abbrev=0)
        release_name="App-$tag-${{ matrix.target }}"

        dotnet publish src/Chirp.CLI.Client/Chirp.CLI.Client.csproj --framework netcoreapp3.1 --runtime "${{ matrix.target }}" -c Release -o "$release_name"

        if [ "${{ matrix.archive }}" == "zip" ]; then
          zip -r "${release_name}.zip" "$release_name"
        else
          tar czvf "${release_name}.tar.gz" "$release_name"
        fi

        rm -r "$release_name"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.zip
          *.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
