name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build, Test, and Release Chirp Executable

    env:
      authentication_github_clientId: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTID }}
      authentication_github_clientSecret: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTSECRET }}
    
    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the solution
    - name: Build the solution
      run: dotnet build Chirp.sln --configuration Release --no-restore

    # Run tests
    - name: Run tests
      run: dotnet test --configuration Release --verbosity normal

    # Publish the binary (only for tagged pushes)
    - name: Publish binary
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet publish Chirp.sln --configuration Release --output ./publish --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true

    # Create GitHub Release (only for tagged pushes)
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') && success()
      with:
        tag_name: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        files: ./publish/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
